using System;
using System.Collections.Generic;

namespace RDOS.BaseLine.RDOSInfratructure
{
    public partial class VisitList
    {
        public Guid Id { get; set; }
        public string VisitId { get; set; } = null!;
        public DateTime? VisitDate { get; set; }
        public string? StartTime { get; set; }
        public double? StartLat { get; set; }
        public double? Startlong { get; set; }
        public double? StartDistance { get; set; }
        public string? ParameterRefId { get; set; }
        public string? AllowStartDistance { get; set; }
        public string? InvalidStartDistanceSelfie { get; set; }
        public string? EndTime { get; set; }
        public double? EndLat { get; set; }
        public double? EndLong { get; set; }
        public double? EndDistance { get; set; }
        public double? AllowEndDistance { get; set; }
        public string? InvalidEndDistanceSelfie { get; set; }
        public double? VisitDuration { get; set; }
        public bool? RemoteVisit { get; set; }
        public string? VisitType { get; set; }
        public string? SimSignalStatus { get; set; }
        public string? NetworkCarrier { get; set; }
        public string? DeviceName { get; set; }
        public string? DeviceImei { get; set; }
        public bool? InternetStatus { get; set; }
        public bool? DebugMode { get; set; }
        public string? SicId { get; set; }
        public string? SicName { get; set; }
        public string? NationId { get; set; }
        public string? NationName { get; set; }
        public string? NationAssigmentId { get; set; }
        public string? NationAssigmentName { get; set; }
        public string? NationAssigmentRole { get; set; }
        public string? BranchId { get; set; }
        public string? BranchName { get; set; }
        public string? BranchAssigmentId { get; set; }
        public string? BranchAssigmentName { get; set; }
        public string? BranchAssigmentRole { get; set; }
        public string? RegionId { get; set; }
        public string? RegionName { get; set; }
        public string? RegionAssigmentId { get; set; }
        public string? RegionAssigmentName { get; set; }
        public string? RegionAssigmentRole { get; set; }
        public string? SubRegionId { get; set; }
        public string? SubRegionName { get; set; }
        public string? SubRegionAssigmentId { get; set; }
        public string? SubRegionAssigmentName { get; set; }
        public string? SubRegionAssigmentRole { get; set; }
        public string? Areaid { get; set; }
        public string? AreaName { get; set; }
        public string? AreaAssigmentId { get; set; }
        public string? AreaAssigmentName { get; set; }
        public string? AreaAssigmentRole { get; set; }
        public string? SubAreaId { get; set; }
        public string? SubAreaName { get; set; }
        public string? SubAreaAssigmentId { get; set; }
        public string? SubAreaAssigmentName { get; set; }
        public string? SubAreaAssigmentRole { get; set; }
        public string? DsaId { get; set; }
        public string? DsaName { get; set; }
        public string? DsaAssigmentId { get; set; }
        public string? DsaAssigmentName { get; set; }
        public string? DsaAssigmentRole { get; set; }
        public string? DistributorId { get; set; }
        public string? DistributorName { get; set; }
        public string? DisShiptoId { get; set; }
        public string? DisShiptoName { get; set; }
        public string? RzId { get; set; }
        public string? RzType { get; set; }
        public string? RzName { get; set; }
        public string? VisitCreatedById { get; set; }
        public string? VisitCreatedByJobTitle { get; set; }
        public string? VisitOwnedById { get; set; }
        public string? VisitOwnedByJobTitle { get; set; }
        public string? CustomerId { get; set; }
        public string? CusShiptoId { get; set; }
        public string? CusShiptoName { get; set; }
        public string? CusShiptoAddress { get; set; }
        public string? CusShiptoPhone { get; set; }
        public string? CusAttId1 { get; set; }
        public string? CusAttId2 { get; set; }
        public string? CusAttId3 { get; set; }
        public string? CusAttId4 { get; set; }
        public string? CusAttId5 { get; set; }
        public string? CusAttId6 { get; set; }
        public string? CusAttId7 { get; set; }
        public string? CusAttId8 { get; set; }
        public string? CusAttId9 { get; set; }
        public string? CusAttId10 { get; set; }
        public string? CusAttName1 { get; set; }
        public string? CusAttName2 { get; set; }
        public string? CusAttName3 { get; set; }
        public string? CusAttName4 { get; set; }
        public string? CusAttName5 { get; set; }
        public string? CusAttName6 { get; set; }
        public string? CusAttName7 { get; set; }
        public string? CusAttName8 { get; set; }
        public string? CusAttName9 { get; set; }
        public string? CusAttName10 { get; set; }
        public string? CusAttCode1 { get; set; }
        public string? CusAttCode2 { get; set; }
        public string? CusAttCode3 { get; set; }
        public string? CusAttCode4 { get; set; }
        public string? CusAttCode5 { get; set; }
        public string? CusAttCode6 { get; set; }
        public string? CusAttCode7 { get; set; }
        public string? CusAttCode8 { get; set; }
        public string? CusAttCode9 { get; set; }
        public string? CusAttCode10 { get; set; }
        public string? CusAttCodeName1 { get; set; }
        public string? CusAttCodeName2 { get; set; }
        public string? CusAttCodeName3 { get; set; }
        public string? CusAttCodeName4 { get; set; }
        public string? CusAttCodeName5 { get; set; }
        public string? CusAttCodeName6 { get; set; }
        public string? CusAttCodeName7 { get; set; }
        public string? CusAttCodeName8 { get; set; }
        public string? CusAttCodeName9 { get; set; }
        public string? CusAttCodeName10 { get; set; }
        public double? OutletBaseLat { get; set; }
        public double? OutletBaseLong { get; set; }
        public string? OutletProfileImage { get; set; }
        public string? RegisteredMerchanImage { get; set; }
        public string? VisitStatus { get; set; }
        public string? CreatedBy { get; set; }
        public DateTime CreatedDate { get; set; }
        public string? UpdatedBy { get; set; }
        public DateTime? UpdatedDate { get; set; }
        public string? ReasonCode { get; set; }
        public string? ReasonDesc { get; set; }
        public string? ShopClosedImage { get; set; }
        public string? SalesOrgId { get; set; }
        public string? SalesOrgDesc { get; set; }
        public DateTime? EndDate { get; set; }
        public string? TaskId { get; set; }
        public string? TaskDesc { get; set; }
        public string? TaskCode { get; set; }
        public string? TaskCodeDesc { get; set; }
        public string? RzSuppervisorId { get; set; }
        public string? RzSuppervisorName { get; set; }
    }
}
