DROP FUNCTION collectrawso(baselinedate VARCHAR, settingref VARCHAR, workingday VARCHAR);
CREATE FUNCTION collectrawso(baselinedate VARCHAR, settingref VARCHAR, workingday VARCHAR) RETURNS TABLE (
	"Id" uuid,
	"BaselineDate" timestamp,
	"BaselineSettingRef" varchar(50),
	"RecordPerformance" boolean,
	"RecordPerformanceUpdateDateTime" timestamp,
	"RecordPerformanceUpdateBy" varchar(255),
	"WorkingDay" boolean,
	"SalesPeriodId" varchar(50),
	"VisitDate" timestamp,
	"VisitId" varchar(255),
	"SOSource" varchar(100),
	"OrderRefNumber" varchar(50),
	"TransactionDate" timestamp,
	"CompletedDate" timestamp,
	"ReferenceRefNbr" varchar(100),
	"OrderDescription" varchar(255),
	"SOCreatedBy" varchar(100),
	"SOOwnerId" varchar(100),
	"CancelDate" timestamp,
	"IsReturn" boolean,
	"ReturnNbr" varchar(100),
	"IsDirect" boolean,
	"OrderType" varchar(100),
	"IsPrintedDeliveryNote" boolean,
	"PrintedDeliveryNoteCount" integer,
	"LastedDeliveryNotePrintDate" timestamp,
	"MenuType" varchar(100),
	"ExpectShippedDate" timestamp,
	"ExpectDeliveryNote" varchar(255),
	"Note" varchar(255),
	"TotalLine" integer,
	"ReasonId" varchar(100),
	"ReasonDesc" varchar(255),
	"NotInSubroute" boolean,
	"Status" varchar(100),
	"OrigOrdSKUs" integer,
	"OrdSKUs" integer,
	"Shipped_SKUs" integer,
	"OrigOrdQty" integer,
	"OrdQty" integer,
	"ShippedQty" integer,
	"OrigPromotionQty" integer,
	"PromotionQty" integer,
	"ShippedPromotionQty" decimal,
	"OrigOrdAmt" decimal,
	"OrdAmt" decimal,
	"ShippedAmt" decimal,
	"PromotionAmt" decimal,
	"OrigOrdDiscAmt" decimal,
	"OrdDiscAmt" decimal,
	"ShippedDiscAmt" decimal,
	"OrigOrdlineDiscAmt" decimal,
	"OrdlineDiscAmt" decimal,
	"ShippedlineDiscAmt" decimal,
	"OrigOrdExtendAmt" decimal,
	"OrdExtendAmt" decimal,
	"ShippedExtendAmt" decimal,
	"TotalVAT" decimal,
	"ConfirmCount" integer,
	"DiscountId" varchar(100),
	"DiscountFullName" varchar(255),
	"DiscountFullShortName" varchar(255),
	"DiscountScheme" varchar(255),
	"PrincipalId" varchar(100),
	"PrincipalDesc" varchar(255),
	"SalesOrgId" varchar(100),
	"SalesOrgDesc" varchar(255),
	"BranchId" varchar(100),
	"BranchName" varchar(255),
	"RegionId" varchar(100),
	"RegionName" varchar(255),
	"SubRegionId" varchar(100),
	"SubRegionName" varchar(255),
	"AreaId" varchar(100),
	"AreaName" varchar(255),
	"SubAreaId" varchar(100),
	"SubAreaName" varchar(255),
	"DSAId" varchar(100),
	"DSADesc" varchar(255),
	"DistributorId" varchar(100),
	"DistributorName" varchar(255),
	"DistyBillToId" varchar(100),
	"WarehouseId" varchar(100),
	"WarehouseName" varchar(255),
	"SICId" varchar(100),
	"SICDesc" varchar(255),
	"RouteZoneId" varchar(100),
	"RouteZoneDesc" varchar(255),
	"RouteZoneType" varchar(100),
	"RouteZonelocation" varchar(100),
	"CustomerId" varchar(100),
	"CustomerName" varchar(255),
	"CustomerCountrysId" varchar(100),
	"CustomerCountrysDesc" varchar(255),
	"CustomerCountrysShortName" varchar(255),
	"CustomerStatesId" varchar(100),
	"CustomerStatesDesc" varchar(255),
	"CustomerStatesShortName" varchar(255),
	"CustomerProvincesId" varchar(100),
	"CustomerProvincesDesc" varchar(255),
	"CustomerProvincesShortName" varchar(255),
	"CustomerCitysId" varchar(100),
	"CustomerCitysDesc" varchar(255),
	"CustomerCitysShortName" varchar(255),
	"CustomerDistrictsId" varchar(100),
	"CustomerDistrictsDesc" varchar(255),
	"CustomerDistrictsShortName" varchar(255),
	"CustomerWardsId" varchar(100),
	"CustomerWardsDesc" varchar(255),
	"CustomerWardsShortName" varchar(255),
	"CustomerStreet" varchar(255),
	"CustomerDeptNo" varchar(255),
	"CustomerLongtiue" double precision,
	"CustomerLattitue" double precision,
	"CustomerShiptoId" varchar(100),
	"CustomerShiptoName" varchar(255),
	"CustomerShiptoCountryId" varchar(100),
	"CustomerShiptoCountryDesc" varchar(255),
	"CustomerShiptoStateId" varchar(100),
	"CustomerShiptoStateDesc" varchar(255),
	"CustomerShiptoProvinceId" varchar(100),
	"CustomerShiptoProvinceDesc" varchar(255),
	"CustomerShiptoCityId" varchar(100),
	"CustomerShiptoDesc" varchar(255),
	"CustomerShiptoDistrictId" varchar(100),
	"CustomerShiptoDistrictDesc" varchar(255),
	"CustomerShiptoWardId" varchar(100),
	"CustomerShiptoWardDesc" varchar(255),
	"CustomerShiptoStreet" varchar(100),
	"CustomerShiptoDeptNo" varchar(255),
	"CustomerShiptoLongtiue" varchar(255),
	"CustomerShiptoLattitue" varchar(255),
	"CustomerPhone" varchar(255),
	"CustomerAddress" varchar(255),
	"NSDManagerId" varchar(100),
	"NSDManagerEmpName" varchar(255),
	"BranchManagerId" varchar(100),
	"BranchManagerEmpName" varchar(255),
	"RegionManagerId" varchar(100),
	"RegionManagerEmpName" varchar(255),
	"SubRegionManagerId" varchar(100),
	"SubRegionManagerEmpName" varchar(255),
	"AreaManagerId" varchar(100),
	"AreaManagerEmpName" varchar(255),
	"SubAreaManagerId" varchar(100),
	"SubAreaManagerEmpName" varchar(255),
	"DSAManagerId" varchar(100),
	"DSAManagerEmpName" varchar(255),
	"RZSuppervisorId" varchar(100),
	"RZSuppervisorEmpName" varchar(255),
	"SalesRepId" varchar(100),
	"SalesRepEmpName" varchar(255),
	"CusShiptoAttributeId1" varchar(100),
	"CusShiptoAttributeName1" varchar(255),
	"CusShiptoAttributeDesc1" varchar(255),
	"CusShiptoAttributeValueId1" varchar(100),
	"CusShiptoAttributeValueDesc1" varchar(255),
	"CusShiptoAttributeId2" varchar(100),
	"CusShiptoAttributeName2" varchar(255),
	"CusShiptoAttributeDesc2" varchar(255),
	"CusShiptoAttributeValueId2" varchar(100),
	"CusShiptoAttributeValueDesc2" varchar(255),
	"CusShiptoAttributeId3" varchar(100),
	"CusShiptoAttributeName3" varchar(255),
	"CusShiptoAttributeDesc3" varchar(255),
	"CusShiptoAttributeValueId3" varchar(100),
	"CusShiptoAttributeValueDesc3" varchar(255),
	"CusShiptoAttributeId4" varchar(100),
	"CusShiptoAttributeName4" varchar(255),
	"CusShiptoAttributeDesc4" varchar(255),
	"CusShiptoAttributeValueId4" varchar(100),
	"CusShiptoAttributeValueDesc4" varchar(255),
	"CusShiptoAttributeId5" varchar(100),
	"CusShiptoAttributeName5" varchar(255),
	"CusShiptoAttributeDesc5" varchar(255),
	"CusShiptoAttributeValueId5" varchar(100),
	"CusShiptoAttributeValueDesc5" varchar(255),
	"CusShiptoAttributeId6" varchar(100),
	"CusShiptoAttributeName6" varchar(255),
	"CusShiptoAttributeDesc6" varchar(255),
	"CusShiptoAttributeValueId6" varchar(100),
	"CusShiptoAttributeValueDesc6" varchar(255),
	"CusShiptoAttributeId7" varchar(100),
	"CusShiptoAttributeName7" varchar(255),
	"CusShiptoAttributeDesc7" varchar(255),
	"CusShiptoAttributeValueId7" varchar(100),
	"CusShiptoAttributeValueDesc7" varchar(255),
	"CusShiptoAttributeId8" varchar(100),
	"CusShiptoAttributeName8" varchar(255),
	"CusShiptoAttributeDesc8" varchar(255),
	"CusShiptoAttributeValueId8" varchar(100),
	"CusShiptoAttributeValueDesc8" varchar(255),
	"CusShiptoAttributeId9" varchar(100),
	"CusShiptoAttributeName9" varchar(255),
	"CusShiptoAttributeDesc9" varchar(255),
	"CusShiptoAttributeValueId9" varchar(100),
	"CusShiptoAttributeValueDesc9" varchar(255),
	"CusShiptoAttributeId10" varchar(100),
	"CusShiptoAttributeName10" varchar(255),
	"CusShiptoAttributeDesc10" varchar(255),
	"CusShiptoAttributeValueId10" varchar(100),
	"CusShiptoAttributeValueDesc10" varchar(255),
	"InventoryId" varchar(100),
	"InventoryShortName" varchar(255),
	"InventoryReportName" varchar(255),
	"InventoryDescription" varchar(255),
	"ERPId" varchar(100),
	"ItemId" varchar(100),
	"ItemGroupId" varchar(100),
	"ItemGroupDesc" varchar(255),
	"KITId" varchar(100),
	"IsKIT" boolean,
	"KITShortName" varchar(255),
	"KITDescription" varchar(255),
	"IsFree" boolean,
	"UnitPrice" decimal,
	"BaseUnitId" varchar(100),
	"BaseUnitDesc" varchar(255),
	"SalesUnitId" varchar(100),
	"SalesUnitDesc" varchar(255),
	"PurchaseUnitId" varchar(100),
	"PurchaseUnitDesc" Varchar(255),
	"Hierarchy" uuid,
	"KitKey" varchar(255),
	"VATId" varchar(100),
	"VATValue" numeric,
	"VAT" numeric,
	"LocationId" varchar(100),
	"LocationDesc" varchar(255),
	"OriginalOrderQuantities" integer,
	"OriginalOrderBaseQuantities" integer,
	"OrderQuantities" integer,
	"OrderBaseQuantities" integer,
	"ShippedQuantities" integer,
	"ShippedBaseQuantities" integer,
	"FailedBaseQuantities" integer,
	"FailedQuantities" integer,
	"ShippingQuantities" integer,
	"ShippingBaseQuantities" integer,
	"RemainQuantities" integer,
	"UOM" varchar(100),
	"UnitRate" integer,
	"ItemPoint" integer,
	"ReturnBaseQuantities" integer,
	"ReturnQuantities" integer,
	"TradePromotionType" varchar(100),
	"PromotionId" varchar(100),
	"PromotionShortName" varchar(255),
	"PromotionFullName" varchar(255),
	"PromotionScheme" varchar(255),
	"ProgramCustomersDetailId" varchar(100),
	"ProgramCustomersShortName" varchar(255),
	"ProgramCustomersFullName" varchar(255),
	"RewardId" varchar(255),
	"RewardDescription" varchar(255),
	"OrigOrdLineAmt" decimal,
	"OrdLineAmt" decimal,
	"ShippedLineAmt" decimal,
	"OrigOrdLineExtendAmt" decimal,
	"OrdLineExtendAmt" decimal,
	"ShippedLineExtendAmt" decimal,
	"DisCountAmount" decimal,
	"DiscountPercented" decimal,
	"InventoryAttributeId1" varchar(100),
	"InventoryAttributeName1" varchar(255),
	"InventoryAttributeDesc1" varchar(255),
	"InventoryAttributeValueId1" varchar(100),
	"InventoryAttributeValueDesc1" varchar(255),
	"InventoryAttributeId2" varchar(100),
	"InventoryAttributeName2" varchar(255),
	"InventoryAttributeDesc2" varchar(255),
	"InventoryAttributeValueId2" varchar(100),
	"InventoryAttributeValueDesc2" varchar(255),
	"InventoryAttributeId3" varchar(100),
	"InventoryAttributeName3" varchar(255),
	"InventoryAttributeDesc3" varchar(255),
	"InventoryAttributeValueId3" varchar(100),
	"InventoryAttributeValueDesc3" varchar(255),
	"InventoryAttributeId4" varchar(100),
	"InventoryAttributeName4" varchar(255),
	"InventoryAttributeDesc4" varchar(255),
	"InventoryAttributeValueId4" varchar(100),
	"InventoryAttributeValueDesc4" varchar(255),
	"InventoryAttributeId5" varchar(100),
	"InventoryAttributeName5" varchar(255),
	"InventoryAttributeDesc5" varchar(255),
	"InventoryAttributeValueId5" varchar(100),
	"InventoryAttributeValueDesc5" varchar(255),
	"InventoryAttributeId6" varchar(100),
	"InventoryAttributeName6" varchar(255),
	"InventoryAttributeDesc6" varchar(255),
	"InventoryAttributeValueId6" varchar(100),
	"InventoryAttributeValueDesc6" varchar(255),
	"InventoryAttributeId7" varchar(100),
	"InventoryAttributeName7" varchar(255),
	"InventoryAttributeDesc7" varchar(255),
	"InventoryAttributeValueId7" varchar(100),
	"InventoryAttributeValueDesc7" varchar(255),
	"InventoryAttributeId8" varchar(100),
	"InventoryAttributeName8" varchar(255),
	"InventoryAttributeDesc8" varchar(255),
	"InventoryAttributeValueId8" varchar(100),
	"InventoryAttributeValueDesc8" varchar(255),
	"InventoryAttributeId9" varchar(100),
	"InventoryAttributeName9" varchar(255),
	"InventoryAttributeDesc9" varchar(255),
	"InventoryAttributeValueId9" varchar(100),
	"InventoryAttributeValueDesc9" varchar(255),
	"InventoryAttributeId10" varchar(100),
	"InventoryAttributeName10" varchar(255),
	"InventoryAttributeDesc10" varchar(255),
	"InventoryAttributeValueId10" varchar(100),
	"InventoryAttributeValueDesc10" varchar(255),
	"CreatedDate" timestamp,
	"UpdatedDate" timestamp,
	"CreatedBy" character varying(250),
	"UpdatedBy" character varying(250),
	"IsDeleted" boolean
) LANGUAGE plpgsql AS $func$ BEGIN
	RETURN QUERY
	Select
		uuid_generate_v4() :: uuid, -- as "Id",
		CAST(baselinedate AS timestamp) :: timestamp, -- as "BaselineDate",
		settingref :: varchar(50), -- as "BaselineSettingRef",
		CASE WHEN CAST(soOrderInfo."OrderDate" AS DATE) = CAST(baselinedate AS DATE) THEN true ELSE false END :: boolean, -- OrderDate = BaselineDate => true
		NULL :: timestamp, --"RecordPerformanceUpdateDateTime"
		NULL :: varchar(255), --"RecordPerformanceUpdateBy"
		CAST(workingday as boolean) :: boolean, -- neu roi vao ngay nghi ngay le theo sales period thi bang false
		soOrderInfo."PeriodID" :: varchar(50), --as "SalesPeriodId",
		soOrderInfo."VisitDate" :: timestamp, --as "VisitDate",
		soOrderInfo."VisitID" :: varchar(255), --as "VisitId",
		soOrderInfo."Source" :: varchar(100), --as "SOSource",
		soOrderInfo."OrderRefNumber" :: varchar(50), --as "OrderRefNumber",
		soOrderInfo."OrderDate" :: timestamp, --as "TransactionDate",
		soOrderInfo."CompleteDate" :: timestamp, --as "CompletedDate",
		soOrderInfo."ReferenceRefNbr" :: varchar(100), --as "ReferenceRefNbr",
		soOrderInfo."OrderDescription" :: varchar(255), --as "OrderDescription",
		soOrderInfo."CreatedBy" :: varchar(100), --as "SOCreatedBy",
		soOrderInfo."Owner_ID" :: varchar(100), --as "SOOwnerId",
		soOrderInfo."CancelDate" :: timestamp, --as "CancelDate",
		soOrderInfo."isReturn" :: boolean, --as "IsReturn",
		soOrderInfo."OrderRefNumber" :: varchar(100), --as "ReturnNbr",
		soOrderInfo."IsDirect" :: boolean, --as "IsDirect",
		soOrderInfo."OrderType" :: varchar(100), --as "OrderType",
		soOrderInfo."IsPrintedDeliveryNote" :: boolean, --as "IsPrintedDeliveryNote",
		soOrderInfo."PrintedDeliveryNoteCount" :: integer, --as "PrintedDeliveryNoteCount",
		soOrderInfo."LastedDeliveryNotePrintDate" :: timestamp, --as "LastedDeliveryNotePrintDate",
		soOrderInfo."MenuType" :: varchar(100), --as "MenuType",
		soOrderInfo."ExpectShippedDate" :: timestamp, --as "ExpectShippedDate",
		soOrderInfo."ExpectDeliveryNote" :: varchar(255), --as "ExpectDeliveryNote",
		soOrderInfo."Note" :: varchar(255), --as "Note",
		soOrderInfo."TotalLine" :: integer, --as "TotalLine",
		soOrderInfo."ReasonCode" :: varchar(100), --as "ReasonId",
		soReasonInfo."Description" :: varchar(255), --as "ReasonDesc",
		soOrderInfo."NotInSubRoute" :: boolean, --as "NotInSubroute",
		soOrderInfo."Status" :: varchar(100), --as "Status",
		soOrderInfo."Orig_Ord_SKUs" :: integer, --as "OrigOrdSKUs",
		soOrderInfo."Ord_SKUs" :: integer, --as "OrdSKUs",
		soOrderInfo."Shipped_SKUs" :: integer, --as "Shipped_SKUs",
		soOrderInfo."Orig_Ord_Qty" :: integer, --as "OrigOrdQty",
		soOrderInfo."Ord_Qty" :: integer, --as "OrdQty",
		soOrderInfo."Shipped_Qty" :: integer, --as "ShippedQty",
		soOrderInfo."Orig_Promotion_Qty" :: integer, --as "OrigPromotionQty",
		soOrderInfo."Promotion_Qty" :: integer, --as "PromotionQty",
		soOrderInfo."Shipped_Promotion_Qty" :: decimal, --as "ShippedPromotionQty",
		soOrderInfo."Orig_Ord_Amt" :: decimal, --as "OrigOrdAmt",
		soOrderInfo."Ord_Amt" :: decimal, --as "OrdAmt",
		soOrderInfo."Shipped_Amt" :: decimal, --as "ShippedAmt",
		soOrderInfo."Promotion_Amt" :: decimal, --as "PromotionAmt",
		soOrderInfo."Orig_Ord_Disc_Amt" :: decimal, --as "OrigOrdDiscAmt",
		soOrderInfo."Ord_Disc_Amt" :: decimal, --as "OrdDiscAmt",
		soOrderInfo."Shipped_Disc_Amt" :: decimal, --as "ShippedDiscAmt",
		soOrderInfo."Orig_Ordline_Disc_Amt" :: decimal, --as "OrigOrdlineDiscAmt",
		soOrderInfo."Ordline_Disc_Amt" :: decimal, --as "OrdlineDiscAmt",
		soOrderInfo."Shipped_line_Disc_Amt" :: decimal, --as "ShippedlineDiscAmt",
		soOrderInfo."Orig_Ord_Extend_Amt" :: decimal, --as "OrigOrdExtendAmt",
		soOrderInfo."Ord_Extend_Amt" :: decimal, --as "OrdExtendAmt",
		soOrderInfo."Shipped_Extend_Amt" :: decimal, --as "ShippedExtendAmt",
		soOrderInfo."TotalVAT" :: decimal, --as "TotalVAT",
		soOrderInfo."ConfirmCount" :: integer, --as "ConfirmCount",
		soOrderInfo."DiscountID" :: varchar(100), --as "DiscountId",
		discount."FullName" :: varchar(255), --as "DiscountFullName",
		discount."ShortName" :: varchar(255), --as "DiscountFullShortName",
		discount."Scheme" :: varchar(255), --as "DiscountScheme",
		soOrderInfo."PrincipalID" :: varchar(100), --as "PrincipalId",
		principalProfile."FullName" :: varchar(255), --as "PrincipalDesc",
		soOrderInfo."SalesOrgID" :: varchar(100), --as "SalesOrgId",
		salesOrgInfo."Description" :: varchar(255), --as "SalesOrgDesc",
		soOrderInfo."BranchId" :: varchar(100), --as "BranchId",
		branchValue."Name" :: varchar(255), --as "BranchName",
		soOrderInfo."RegionId" :: varchar(100), --as "RegionId",
		regionValue."Name" :: varchar(255), --as "RegionName",
		soOrderInfo."SubRegionId" :: varchar(100), --as "SubRegionId",
		subRegionValue."Name" :: varchar(255), --as "SubRegionName",
		soOrderInfo."AreaId" :: varchar(100), --as "AreaId",
		areaValue."Name" :: varchar(255), --as "AreaName",
		soOrderInfo."SubAreaId" :: varchar(100), --as "SubAreaId",
		subAreaValue."Name" :: varchar(255), --as "SubAreaName",
		soOrderInfo."DSAID" :: varchar(100), --as "DSAId",
		dsaInfo."Description" :: varchar(255), --as "DSADesc",
		soOrderInfo."DistributorCode" :: varchar(100), --as "DistributorId",
		distributorInfo."Name" :: varchar(255), --as "DistributorName",
		soOrderInfo."Disty_billtoID" :: varchar(100), --as "DistyBillToId",
		soOrderInfo."WareHouseID" :: varchar(100), --as "WarehouseId",
		wareHouseInfo."ShiptoName" :: varchar(255), --as "WarehouseName",
		soOrderInfo."SIC_ID" :: varchar(100), --as "SICId",
		sicInfo."Description" :: varchar(255), --as "SICDesc",
		soOrderInfo."RouteZoneID" :: varchar(100), --as "RouteZoneId",
		routezoneInfo."Description" :: varchar(255), --as "RouteZoneDesc",
		routezoneInfo."RouteZoneTypeCode" :: varchar(100), --as "RouteZoneType",
		routezoneInfo."LocationCode" :: varchar(100), --as "RouteZonelocation",
		soOrderInfo."CustomerId" :: varchar(100), --as "CustomerId",
		customerInfo."ShortName" :: varchar(255), --as "CustomerName",
		countryInfo."CountryCode" :: varchar(100), --as "CustomerCountrysId",
		countryInfo."Description" :: varchar(255), --as "CustomerCountrysDesc",
		countryInfo."ShortName" :: varchar(255), --as "CustomerCountrysShortName",
		stateInfo."StateCode" :: varchar(100), --as "CustomerStatesId",
		stateInfo."Description" :: varchar(255), --as "CustomerStatesDesc",
		stateInfo."ShortName" :: varchar(255), --as "CustomerStatesShortName",
		provinceInfo."ProvinceCode" :: varchar(100), --as "CustomerProvincesId",
		provinceInfo."Description" :: varchar(255), --as "CustomerProvincesDesc",
		provinceInfo."ShortName" :: varchar(255), --as "CustomerProvincesShortName",
		cityInfo."CityCode" :: varchar(100), --as "CustomerCitysId",
		cityInfo."Description" :: varchar(255), --as "CustomerCitysDesc",
		cityInfo."ShortName" :: varchar(255), --as "CustomerCitysShortName",
		districtInfo."DistrictCode" :: varchar(100), --as "CustomerDistrictsId",
		districtInfo."Description" :: varchar(255), --as "CustomerDistrictsDesc",
		districtInfo."ShortName" :: varchar(255), --as "CustomerDistrictsShortName",
		wardInfo."WardCode" :: varchar(100), --as "CustomerWardsId",
		wardInfo."Description" :: varchar(255), --as "CustomerWardsDesc",
		wardInfo."ShortName" :: varchar(255), --as "CustomerWardsShortName",
		customerInfo."StreetLine" :: varchar(255), --as "CustomerStreet",
		customerInfo."DeptNo" :: varchar(255), --as "CustomerDeptNo",
		customerInfo."Longtiue" :: double precision, --as "CustomerLongtiue",
		customerInfo."Lattitue" :: double precision, --as "CustomerLattitue",
		shiptoCustomer."ShiptoCode" :: varchar(100), --as "CustomerShiptoId",
		shiptoCustomer."ShiptoName" :: varchar(255), --as "CustomerShiptoName",
		shiptoCountryInfo."CountryCode" :: varchar(100), --as "CustomerShiptoCountryId",
		shiptoCountryInfo."Description" :: varchar(255), --as "CustomerShiptoCountryDesc",
		shiptoStateInfo."StateCode" :: varchar(100), --as "CustomerShiptoStateId",
		shiptoStateInfo."Description" :: varchar(255), --as "CustomerShiptoStateDesc",
		shiptoProvinceInfo."ProvinceCode" :: varchar(100), --as "CustomerShiptoProvinceId",
		shiptoProvinceInfo."Description" :: varchar(255), --as "CustomerShiptoProvinceDesc",
		shiptoCityInfo."CityCode" :: varchar(100), --as "CustomerShiptoCityId",
		shiptoCityInfo."Description" :: varchar(255), --as "CustomerShiptoDesc",
		shiptoDistrictInfo."DistrictCode" :: varchar(100), --as "CustomerShiptoDistrictId",
		shiptoDistrictInfo."Description" :: varchar(255), --as "CustomerShiptoDistrictDesc",
		shiptoWardInfo."WardCode" :: varchar(100), --as "CustomerShiptoWardId",
		shiptoWardInfo."Description" :: varchar(255), --as "CustomerShiptoWardDesc",
		shiptoCustomer."Street" :: varchar(100), --as "CustomerShiptoStreet",
		shiptoCustomer."DeptNo" :: varchar(255), --as "CustomerShiptoDeptNo",
		shiptoCustomer."Longtiue" :: varchar(255), --as "CustomerShiptoLongtiue",
		shiptoCustomer."Lattitue" :: varchar(255), --as "CustomerShiptoLattitue",
		soOrderInfo."CustomerPhone" :: varchar(255), --as "CustomerPhone",
		soOrderInfo."CustomerAddress" :: varchar(255), --as "CustomerAddress",
		soOrderInfo."NSD_ID" :: varchar(100), --as "NSDManagerId",
		principleEmployee."FullName" :: varchar(255), --as "NSDManagerEmpName",
		soOrderInfo."Branch_Manager_ID" :: varchar(100), --as "BranchManagerId",
		branchEmployee."FullName" :: varchar(255), --as "BranchManagerEmpName",
		soOrderInfo."Region_Manager_ID" :: varchar(100), --as "RegionManagerId",
		regionEmployee."FullName" :: varchar(255), --as "RegionManagerEmpName",
		soOrderInfo."Sub_Region_Manager_ID" :: varchar(100), --as "SubRegionManagerId",
		subAreaEmployee."FullName" :: varchar(255), --as "SubRegionManagerEmpName",
		soOrderInfo."Area_Manager_ID" :: varchar(100), --as "AreaManagerId",
		areaEmployee."FullName" :: varchar(255), --as "AreaManagerEmpName",
		soOrderInfo."Sub_Area_Manager_ID" :: varchar(100), --as "SubAreaManagerId",
		subAreaEmployee."FullName" :: varchar(255), --as "SubAreaManagerEmpName",
		soOrderInfo."DSA_Manager_ID" :: varchar(100), --as "DSAManagerId",
		dsaEmployee."FullName" :: varchar(255), --as "DSAManagerEmpName",
		soOrderInfo."RZ_Suppervisor_ID" :: varchar(100), --as "RZSuppervisorId",
		routezoneEmployee."FullName" :: varchar(255), --as "RZSuppervisorEmpName",
		soOrderInfo."SalesRepID" :: varchar(100), --as "SalesRepId",
		salesEmployee."FullName" :: varchar(255), --as "SalesRepEmpName",
		cus01Info."AttributeID" :: varchar(100), --as "CusShiptoAttributeId1",
		cus01Info."AttributeName" :: varchar(255), --as "CusShiptoAttributeName1",
		cus01Info."Description" :: varchar(255), --as "CusShiptoAttributeDesc1",
		cus01Attribute."Code" :: varchar(100), --as "CusShiptoAttributeValueId1",
		cus01Attribute."Description" :: varchar(255), --as "CusShiptoAttributeValueDesc1",
		cus02Info."AttributeID" :: varchar(100), --as "CusShiptoAttributeId2",
		cus02Info."AttributeName" :: varchar(255), --as "CusShiptoAttributeName2",
		cus02Info."Description" :: varchar(255), --as "CusShiptoAttributeDesc2",
		cus02Attribute."Code" :: varchar(100), --as "CusShiptoAttributeValueId2",
		cus02Attribute."Description" :: varchar(255), --as "CusShiptoAttributeValueDesc2",
		cus03Info."AttributeID" :: varchar(100), --as "CusShiptoAttributeId3",
		cus03Info."AttributeName" :: varchar(255), --as "CusShiptoAttributeName3",
		cus03Info."Description" :: varchar(255), --as "CusShiptoAttributeDesc3",
		cus03Attribute."Code" :: varchar(100), --as "CusShiptoAttributeValueId3",
		cus03Attribute."Description" :: varchar(255), --as "CusShiptoAttributeValueDesc3",
		cus04Info."AttributeID" :: varchar(100), --as "CusShiptoAttributeId4",
		cus04Info."AttributeName" :: varchar(255), --as "CusShiptoAttributeName4",
		cus04Info."Description" :: varchar(255), --as "CusShiptoAttributeDesc4",
		cus04Attribute."Code" :: varchar(100), --as "CusShiptoAttributeValueId4",
		cus04Attribute."Description" :: varchar(255), --as "CusShiptoAttributeValueDesc4",
		cus05Info."AttributeID" :: varchar(100), --as "CusShiptoAttributeId5",
		cus05Info."AttributeName" :: varchar(255), --as "CusShiptoAttributeName5",
		cus05Info."Description" :: varchar(255), --as "CusShiptoAttributeDesc5",
		cus05Attribute."Code" :: varchar(100), --as "CusShiptoAttributeValueId5",
		cus05Attribute."Description" :: varchar(255), --as "CusShiptoAttributeValueDesc5",
		cus06Info."AttributeID" :: varchar(100), --as "CusShiptoAttributeId6",
		cus06Info."AttributeName" :: varchar(255), --as "CusShiptoAttributeName6",
		cus06Info."Description" :: varchar(255), --as "CusShiptoAttributeDesc6",
		cus06Attribute."Code" :: varchar(100), --as "CusShiptoAttributeValueId6",
		cus06Attribute."Description" :: varchar(255), --as "CusShiptoAttributeValueDesc6",
		cus07Info."AttributeID" :: varchar(100), --as "CusShiptoAttributeId7",
		cus07Info."AttributeName" :: varchar(255), --as "CusShiptoAttributeName7",
		cus07Info."Description" :: varchar(255), --as "CusShiptoAttributeDesc7",
		cus07Attribute."Code" :: varchar(100), --as "CusShiptoAttributeValueId7",
		cus07Attribute."Description" :: varchar(255), --as "CusShiptoAttributeValueDesc7",
		cus08Info."AttributeID" :: varchar(100), --as "CusShiptoAttributeId8",
		cus08Info."AttributeName" :: varchar(255), --as "CusShiptoAttributeName8",
		cus08Info."Description" :: varchar(255), --as "CusShiptoAttributeDesc8",
		cus08Attribute."Code" :: varchar(100), --as "CusShiptoAttributeValueId8",
		cus08Attribute."Description" :: varchar(255), --as "CusShiptoAttributeValueDesc8",
		cus09Info."AttributeID" :: varchar(100), --as "CusShiptoAttributeId9",
		cus09Info."AttributeName" :: varchar(255), --as "CusShiptoAttributeName9",
		cus09Info."Description" :: varchar(255), --as "CusShiptoAttributeDesc9",
		cus09Attribute."Code" :: varchar(100), --as "CusShiptoAttributeValueId9",
		cus09Attribute."Description" :: varchar(255), --as "CusShiptoAttributeValueDesc9",
		cus10Info."AttributeID" :: varchar(100), --as "CusShiptoAttributeId10",
		cus10Info."AttributeName" :: varchar(255), --as "CusShiptoAttributeName10",
		cus10Info."Description" :: varchar(255), --as "CusShiptoAttributeDesc10",
		cus10Attribute."Code" :: varchar(100), --as "CusShiptoAttributeValueId10",
		cus10Attribute."Description" :: varchar(255), --as "CusShiptoAttributeValueDesc10",
		soItemInfo."InventoryID" :: varchar(100), --as "InventoryId",
		inventoryItem."ShortName" :: varchar(255), --as "InventoryShortName",
		inventoryItem."ReportName" :: varchar(255), --as "InventoryReportName",
		inventoryItem."Description" :: varchar(255), --as "InventoryDescription",
		inventoryItem."ERPCode" :: varchar(100), --as "ERPId",
		inventoryItem."InventoryItemId" :: varchar(100), --as "ItemId",
		inventoryItem."GroupId" :: varchar(100), --as "ItemGroupId",
		itemGroupInfo."Description" :: varchar(255), --as "ItemGroupDesc",
		soItemInfo."KitId" :: varchar(100), --as "KITId",
		soItemInfo."IsKit" :: boolean, --as "IsKIT",
		kitInfo."ShortName" :: varchar(255), --as "KITShortName",
		kitInfo."Description" :: varchar(255), --as "KITDescription",
		soItemInfo."IsFree" :: boolean, --as "IsFree",
		soItemInfo."UnitPrice" :: decimal, --as "UnitPrice",
		baseUomInfo."UomId" :: varchar(100), --as "BaseUnitId",
		baseUomInfo."Description" :: varchar(255), --as "BaseUnitDesc",
		salesUomInfo."UomId" :: varchar(100), --as "SalesUnitId",
		salesUomInfo."Description" :: varchar(255), --as "SalesUnitDesc",
		purchaseUomInfo."UomId" :: varchar(100), --as "PurchaseUnitId",
		purchaseUomInfo."Description" :: Varchar(255), --as "PurchaseUnitDesc",
		soItemInfo."Hierarchy" :: uuid, --as "Hierarchy",
		soItemInfo."KitKey" :: varchar(255), --as "KitKey",
		soItemInfo."VATCode" :: varchar(100), --as "VATId",
		soItemInfo."VatValue" :: numeric, --as "VATValue",
		soItemInfo."VAT" :: numeric, --as "VAT",
		soItemInfo."LocationID" :: varchar(100), --as "LocationId",
		locationInfo."Decscription" :: varchar(255), --as "LocationDesc",
		soItemInfo."OriginalOrderQuantities" :: integer, --as "OriginalOrderQuantities",
		soItemInfo."OriginalOrderBaseQuantities" :: integer, --as "OriginalOrderBaseQuantities",
		soItemInfo."OrderQuantities" :: integer, --as "OrderQuantities",
		soItemInfo."OrderBaseQuantities" :: integer, --as "OrderBaseQuantities",
		soItemInfo."ShippedQuantities" :: integer, --as "ShippedQuantities",
		soItemInfo."ShippedBaseQuantities" :: integer, --as "ShippedBaseQuantities",
		soItemInfo."FailedBaseQuantities" :: integer, --as "FailedBaseQuantities",
		soItemInfo."FailedQuantities" :: integer, --as "FailedQuantities",
		soItemInfo."ShippingQuantities" :: integer, --as "ShippingQuantities",
		soItemInfo."ShippingBaseQuantities" :: integer, --as "ShippingBaseQuantities",
		soItemInfo."RemainQuantities" :: integer, --as "RemainQuantities",
		soItemInfo."UOM" :: varchar(100), --as "UOM",
		soItemInfo."UnitRate" :: integer, --as "UnitRate",
		soItemInfo."ItemPoint" :: integer, --as "ItemPoint",
		soItemInfo."ReturnBaseQuantities" :: integer, --as "ReturnBaseQuantities",
		soItemInfo."ReturnQuantities" :: integer, --as "ReturnQuantities",
		soItemInfo."PromotionType" :: varchar(100), --as "TradePromotionType",
		soItemInfo."PromotionCode" :: varchar(100), --as "PromotionId",
		promotionInfo."ShortName" :: varchar(255), --as "PromotionShortName",
		promotionInfo."FullName" :: varchar(255), --as "PromotionFullName",
		promotionInfo."Scheme" :: varchar(255), --as "PromotionScheme",
		case  when soItemInfo."PromotionType" = 'Promotion' then soItemInfo."ProgramCustomersDetailCode" 
				when soItemInfo."PromotionType" = 'Display' then TpDiscounts."Code" 
				when soItemInfo."PromotionType" = 'Accumulate' then NULL  
		else NULL end:: varchar(100), --as "ProgramCustomersDetailId" --Accumulate later,
		case  when soItemInfo."PromotionType" = 'Promotion' then soItemInfo."ProgramCustomersDetailDesc" 
				when soItemInfo."PromotionType" = 'Display' then TpDiscounts."ShortName" 
				when soItemInfo."PromotionType" = 'Accumulate' then NULL  
		else NULL end :: varchar(255), --as "ProgramCustomersShortName",
		case  when soItemInfo."PromotionType" = 'Promotion' then soItemInfo."ProgramCustomersDetailDesc" 
				when soItemInfo."PromotionType" = 'Display' then TpDiscounts."FullName" 
				when soItemInfo."PromotionType" = 'Accumulate' then NULL  
		else NULL end :: varchar(255), --as "ProgramCustomersFullName",
		case when soItemInfo."IsFree" = TRUE then soItemInfo."InventoryID" else NULL end :: varchar(255), --as "RewardId",
		case when soItemInfo."IsFree" = TRUE then soItemInfo."ItemDescription" else NULL end :: varchar(255), --as "RewardDescription",
		soItemInfo."Orig_Ord_Line_Amt" :: decimal, --as "OrigOrdLineAmt",
		soItemInfo."Ord_Line_Amt" :: decimal, --as "OrdLineAmt",
		soItemInfo."Shipped_Line_Amt" :: decimal, --as "ShippedLineAmt",
		soItemInfo."Orig_Ord_Line_Extend_Amt" :: decimal, --as "OrigOrdLineExtendAmt",
		soItemInfo."Ord_Line_Extend_Amt" :: decimal, --as "OrdLineExtendAmt",
		soItemInfo."Shipped_Line_Extend_Amt" :: decimal, --as "ShippedLineExtendAmt",
		soItemInfo."DisCountAmount" :: decimal, --as "DisCountAmount",
		soItemInfo."DiscountPercented" :: decimal, --as "DiscountPercented",
		itemSetting1."AttributeId" :: varchar(100), --as "InventoryAttributeId1",
		itemSetting1."AttributeName" :: varchar(255), --as "InventoryAttributeName1",
		itemSetting1."Description" :: varchar(255), --as "InventoryAttributeDesc1",
		itemAttribute1."ItemAttributeCode" :: varchar(100), --as "InventoryAttributeValueId1",
		itemAttribute1."Description" :: varchar(255), --as "InventoryAttributeValueDesc1",
		itemSetting2."AttributeId" :: varchar(100), --as "InventoryAttributeId2",
		itemSetting2."AttributeName" :: varchar(255), --as "InventoryAttributeName2",
		itemSetting2."Description" :: varchar(255), --as "InventoryAttributeDesc2",
		itemAttribute2."ItemAttributeCode" :: varchar(100), --as "InventoryAttributeValueId2",
		itemAttribute2."Description" :: varchar(255), --as "InventoryAttributeValueDesc2",
		itemSetting3."AttributeId" :: varchar(100), --as "InventoryAttributeId3",
		itemSetting3."AttributeName" :: varchar(255), --as "InventoryAttributeName3",
		itemSetting3."Description" :: varchar(255), --as "InventoryAttributeDesc3",
		itemAttribute3."ItemAttributeCode" :: varchar(100), --as "InventoryAttributeValueId3",
		itemAttribute3."Description" :: varchar(255), --as "InventoryAttributeValueDesc3",
		itemSetting4."AttributeId" :: varchar(100), --as "InventoryAttributeId4",
		itemSetting4."AttributeName" :: varchar(255), --as "InventoryAttributeName4",
		itemSetting4."Description" :: varchar(255), --as "InventoryAttributeDesc4",
		itemAttribute4."ItemAttributeCode" :: varchar(100), --as "InventoryAttributeValueId4",
		itemAttribute4."Description" :: varchar(255), --as "InventoryAttributeValueDesc4",
		itemSetting5."AttributeId" :: varchar(100), --as "InventoryAttributeId5",
		itemSetting5."AttributeName" :: varchar(255), --as "InventoryAttributeName5",
		itemSetting5."Description" :: varchar(255), --as "InventoryAttributeDesc5",
		itemAttribute5."ItemAttributeCode" :: varchar(100), --as "InventoryAttributeValueId5",
		itemAttribute5."Description" :: varchar(255), --as "InventoryAttributeValueDesc5",
		itemSetting6."AttributeId" :: varchar(100), --as "InventoryAttributeId6",
		itemSetting6."AttributeName" :: varchar(255), --as "InventoryAttributeName6",
		itemSetting6."Description" :: varchar(255), --as "InventoryAttributeDesc6",
		itemAttribute6."ItemAttributeCode" :: varchar(100), --as "InventoryAttributeValueId6",
		itemAttribute6."Description" :: varchar(255), --as "InventoryAttributeValueDesc6",
		itemSetting7."AttributeId" :: varchar(100), --as "InventoryAttributeId7",
		itemSetting7."AttributeName" :: varchar(255), --as "InventoryAttributeName7",
		itemSetting7."Description" :: varchar(255), --as "InventoryAttributeDesc7",
		itemAttribute7."ItemAttributeCode" :: varchar(100), --as "InventoryAttributeValueId7",
		itemAttribute7."Description" :: varchar(255), --as "InventoryAttributeValueDesc7",
		itemSetting8."AttributeId" :: varchar(100), --as "InventoryAttributeId8",
		itemSetting8."AttributeName" :: varchar(255), --as "InventoryAttributeName8",
		itemSetting8."Description" :: varchar(255), --as "InventoryAttributeDesc8",
		itemAttribute8."ItemAttributeCode" :: varchar(100), --as "InventoryAttributeValueId8",
		itemAttribute8."Description" :: varchar(255), --as "InventoryAttributeValueDesc8",
		itemSetting9."AttributeId" :: varchar(100), --as "InventoryAttributeId9",
		itemSetting9."AttributeName" :: varchar(255), --as "InventoryAttributeName9",
		itemSetting9."Description" :: varchar(255), --as "InventoryAttributeDesc9",
		itemAttribute9."ItemAttributeCode" :: varchar(100), --as "InventoryAttributeValueId9",
		itemAttribute9."Description" :: varchar(255), --as "InventoryAttributeValueDesc9",
		itemSetting10."AttributeId" :: varchar(100), --as "InventoryAttributeId10",
		itemSetting10."AttributeName" :: varchar(255), --as "InventoryAttributeName10",
		itemSetting10."Description" :: varchar(255), --as "InventoryAttributeDesc10",
		itemAttribute10."ItemAttributeCode" :: varchar(100), --as "InventoryAttributeValueId10",
		itemAttribute10."Description" :: varchar(255), --as "InventoryAttributeValueDesc10",
		soOrderInfo."CreatedDate" :: timestamp, --as "CreatedDate",
		soOrderInfo."UpdatedDate" :: timestamp, --as "UpdatedDate",
		soOrderInfo."CreatedBy" :: character varying(250), --as "CreatedBy",
		soOrderInfo."UpdatedBy" :: character varying(250), --as "UpdatedBy",
		soOrderInfo."IsDeleted" :: boolean --as "IsDeleted"
	From 
		"SO_OrderItems" as soItemInfo
		join "SO_OrderInformations" as soOrderInfo on soOrderInfo."OrderRefNumber" = soItemInfo."OrderRefNumber"
		left join "SO_Reasons" as soReasonInfo on soReasonInfo."ReasonCode" = soOrderInfo."ReasonCode"
		join "PrincipalProfile" as principalProfile on principalProfile."Code" = soOrderInfo."PrincipalID"
		join "SC_SalesOrganizationStructures" as salesOrgInfo on salesOrgInfo."Code" = soOrderInfo."SalesOrgID"
		left join "SC_TerritoryValues" as branchValue on branchValue."Key" = concat('TL01-',soOrderInfo."BranchId")
		left join "SC_TerritoryValues" as regionValue on regionValue."Key" = concat('TL02-',soOrderInfo."RegionId")
		left join "SC_TerritoryValues" as subRegionValue on subRegionValue."Key" = concat('TL03-',soOrderInfo."SubRegionId")
		left join "SC_TerritoryValues" as areaValue on areaValue."Key" = concat('TL04-',soOrderInfo."AreaId")
		left join "SC_TerritoryValues" as subAreaValue on subAreaValue."Key" = concat('TL05-',soOrderInfo."SubAreaId")
		join "DSA_DistributorSellingAreas" as dsaInfo on dsaInfo."Code" = soOrderInfo."DSAID"
		join "Distributors" as distributorInfo on distributorInfo."Code" = soOrderInfo."DistributorCode"
		join "DistributorShiptos" as wareHouseInfo on wareHouseInfo."ShiptoCode" = soOrderInfo."WareHouseID"
		and wareHouseInfo."DistributorId" = distributorInfo."Id"
		join "PrimarySics" as sicInfo on sicInfo."Code" = soOrderInfo."SIC_ID"
		left join "RZ_RouteZoneInfomations" as routezoneInfo on routezoneInfo."RouteZoneCode" = soOrderInfo."RouteZoneID"
		join "CustomerInformations" as customerInfo on customerInfo."CustomerCode" = soOrderInfo."CustomerId"
		left join "Countrys" as countryInfo on countryInfo."Id" = customerInfo."Country"
		left join "States" as stateInfo on stateInfo."Id" = customerInfo."State"
		left join "Provinces" as provinceInfo on provinceInfo."Id" = customerInfo."Province"
		left join "Districts" as districtInfo on districtInfo."Id" = customerInfo."District"
		left join "Wards" as wardInfo on wardInfo."Id" = customerInfo."Wards"
		left join "Citys" as cityInfo on cityInfo."Id" = customerInfo."City"
		join "CustomerShiptos" as shiptoCustomer on shiptoCustomer."CustomerInfomationId" = customerInfo."Id"
		and shiptoCustomer."ShiptoCode" = soOrderInfo."CustomerShiptoID"
		left join "Countrys" as shiptoCountryInfo on shiptoCountryInfo."Id" = shiptoCustomer."Country"
		left join "States" as shiptoStateInfo on shiptoStateInfo."Id" = shiptoCustomer."State"
		left join "Provinces" as shiptoProvinceInfo on shiptoProvinceInfo."Id" = shiptoCustomer."Province"
		left join "Districts" as shiptoDistrictInfo on shiptoDistrictInfo."Id" = shiptoCustomer."District"
		left join "Wards" as shiptoWardInfo on shiptoWardInfo."Id" = shiptoCustomer."Wards"
		left join "Citys" as shiptoCityInfo on shiptoCityInfo."Id" = shiptoCustomer."City"
		left join "PrincipleEmployees" as principleEmployee on principleEmployee."EmployeeCode" = soOrderInfo."NSD_ID"
		left join "PrincipleEmployees" as branchEmployee on branchEmployee."EmployeeCode" = soOrderInfo."Branch_Manager_ID"
		left join "PrincipleEmployees" as regionEmployee on regionEmployee."EmployeeCode" = soOrderInfo."Region_Manager_ID"
		left join "PrincipleEmployees" as subRegionEmployee on subRegionEmployee."EmployeeCode" = soOrderInfo."Sub_Region_Manager_ID"
		left join "PrincipleEmployees" as areaEmployee on areaEmployee."EmployeeCode" = soOrderInfo."Area_Manager_ID"
		left join "PrincipleEmployees" as subAreaEmployee on subAreaEmployee."EmployeeCode" = soOrderInfo."Sub_Area_Manager_ID"
		left join "PrincipleEmployees" as dsaEmployee on dsaEmployee."EmployeeCode" = soOrderInfo."DSA_Manager_ID"
		left join "PrincipleEmployees" as routezoneEmployee on routezoneEmployee."EmployeeCode" = soOrderInfo."RZ_Suppervisor_ID"
		left join "PrincipleEmployees" as salesEmployee on salesEmployee."EmployeeCode" = soOrderInfo."SalesRepID"
		join "CustomerSettings" as cus01Info on cus01Info."AttributeID" = 'CUS01'
		left join "CustomerAttributes" as cus01Attribute on cus01Attribute."Code" = soOrderInfo."Shipto_Attribute1" and cus01Attribute."AttributeMaster" = cus01Info."AttributeName"
		join "CustomerSettings" as cus02Info on cus02Info."AttributeID" = 'CUS02'
		left join "CustomerAttributes" as cus02Attribute on cus02Attribute."Code" = soOrderInfo."Shipto_Attribute2" and cus02Attribute."AttributeMaster" = cus02Info."AttributeName"
		join "CustomerSettings" as cus03Info on cus03Info."AttributeID" = 'CUS03'
		left join "CustomerAttributes" as cus03Attribute on cus03Attribute."Code" = soOrderInfo."Shipto_Attribute3" and cus03Attribute."AttributeMaster" = cus03Info."AttributeName"
		join "CustomerSettings" as cus04Info on cus04Info."AttributeID" = 'CUS04'
		left join "CustomerAttributes" as cus04Attribute on cus04Attribute."Code" = soOrderInfo."Shipto_Attribute4" and cus04Attribute."AttributeMaster" = cus04Info."AttributeName"
		join "CustomerSettings" as cus05Info on cus05Info."AttributeID" = 'CUS05'
		left join "CustomerAttributes" as cus05Attribute on cus05Attribute."Code" = soOrderInfo."Shipto_Attribute5" and cus05Attribute."AttributeMaster" = cus05Info."AttributeName"
		join "CustomerSettings" as cus06Info on cus06Info."AttributeID" = 'CUS06'
		left join "CustomerAttributes" as cus06Attribute on cus06Attribute."Code" = soOrderInfo."Shipto_Attribute6" and cus06Attribute."AttributeMaster" = cus06Info."AttributeName"
		join "CustomerSettings" as cus07Info on cus07Info."AttributeID" = 'CUS07'
		left join "CustomerAttributes" as cus07Attribute on cus07Attribute."Code" = soOrderInfo."Shipto_Attribute7" and cus01Attribute."AttributeMaster" = cus07Info."AttributeName"
		join "CustomerSettings" as cus08Info on cus08Info."AttributeID" = 'CUS08'
		left join "CustomerAttributes" as cus08Attribute on cus08Attribute."Code" = soOrderInfo."Shipto_Attribute8" and cus08Attribute."AttributeMaster" = cus08Info."AttributeName"
		join "CustomerSettings" as cus09Info on cus09Info."AttributeID" = 'CUS09'
		left join "CustomerAttributes" as cus09Attribute on cus09Attribute."Code" = soOrderInfo."Shipto_Attribute1" and cus09Attribute."AttributeMaster" = cus09Info."AttributeName"
		join "CustomerSettings" as cus10Info on cus10Info."AttributeID" = 'CUS10'
		left join "CustomerAttributes" as cus10Attribute on cus10Attribute."Code" = soOrderInfo."Shipto_Attribute10" and cus10Attribute."AttributeMaster" = cus10Info."AttributeName"
		left join "InventoryItems" as inventoryItem on inventoryItem."InventoryItemId" = soItemInfo."ItemCode"
		left join "ItemGroups" as itemGroupInfo on itemGroupInfo."Code" = inventoryItem."GroupId"
		left join "ItemAttributes" as itemAttribute1 on itemAttribute1."Id" = inventoryItem."Attribute1"
		left join "ItemSettings" as itemSetting1 on itemSetting1."AttributeId" = itemAttribute1."ItemAttributeMaster"
		left join "ItemAttributes" as itemAttribute2 on itemAttribute2."Id" = inventoryItem."Attribute2"
		left join "ItemSettings" as itemSetting2 on itemSetting2."AttributeId" = itemAttribute2."ItemAttributeMaster"
		left join "ItemAttributes" as itemAttribute3 on itemAttribute3."Id" = inventoryItem."Attribute3"
		left join "ItemSettings" as itemSetting3 on itemSetting3."AttributeId" = itemAttribute3."ItemAttributeMaster"
		left join "ItemAttributes" as itemAttribute4 on itemAttribute4."Id" = inventoryItem."Attribute4"
		left join "ItemSettings" as itemSetting4 on itemSetting4."AttributeId" = itemAttribute4."ItemAttributeMaster"
		left join "ItemAttributes" as itemAttribute5 on itemAttribute5."Id" = inventoryItem."Attribute5"
		left join "ItemSettings" as itemSetting5 on itemSetting5."AttributeId" = itemAttribute5."ItemAttributeMaster"
		left join "ItemAttributes" as itemAttribute6 on itemAttribute6."Id" = inventoryItem."Attribute6"
		left join "ItemSettings" as itemSetting6 on itemSetting6."AttributeId" = itemAttribute6."ItemAttributeMaster"
		left join "ItemAttributes" as itemAttribute7 on itemAttribute7."Id" = inventoryItem."Attribute7"
		left join "ItemSettings" as itemSetting7 on itemSetting7."AttributeId" = itemAttribute7."ItemAttributeMaster"
		left join "ItemAttributes" as itemAttribute8 on itemAttribute8."Id" = inventoryItem."Attribute8"
		left join "ItemSettings" as itemSetting8 on itemSetting8."AttributeId" = itemAttribute8."ItemAttributeMaster"
		left join "ItemAttributes" as itemAttribute9 on itemAttribute9."Id" = inventoryItem."Attribute9"
		left join "ItemSettings" as itemSetting9 on itemSetting9."AttributeId" = itemAttribute9."ItemAttributeMaster"
		left join "ItemAttributes" as itemAttribute10 on itemAttribute10."Id" = inventoryItem."Attribute10"
		left join "ItemSettings" as itemSetting10 on itemSetting10."AttributeId" = itemAttribute10."ItemAttributeMaster"
		left join "Kits" as kitInfo on kitInfo."Id" = soItemInfo."KitId"
		left join "Uoms" as baseUomInfo on baseUomInfo."Id" = soItemInfo."BaseUnit"
		left join "Uoms" as purchaseUomInfo on purchaseUomInfo."Id" = soItemInfo."PurchaseUnit"
		left join "Uoms" as salesUomInfo on salesUomInfo."Id" = soItemInfo."SalesUnit"
		left join "PrincipalWarehouseLocations" as locationInfo on locationInfo."Code" = CAST(soItemInfo."LocationID" AS INT)
		left join "TpPromotions" as promotionInfo on promotionInfo."PromotionType" = soItemInfo."PromotionType" 
		and promotionInfo."Code" = soItemInfo."PromotionCode"
		left join "TpDiscounts" as TpDiscounts on TpDiscounts."Code" = soItemInfo."PromotionCode"
		left join "TpDiscounts" as discount on discount."Code" = soItemInfo."DiscountID"
		Where soItemInfo."IsDeleted" = false
		and CAST(baselinedate AS DATE) =
			CASE WHEN soOrderInfo."UpdatedDate" IS NULL THEN CAST(soOrderInfo."CreatedDate" AS DATE)
			ELSE CAST(soOrderInfo."UpdatedDate" AS DATE)
			END
		and CASE WHEN soOrderInfo."ReasonCode" IS NOT NULL THEN soReasonInfo."IsDeleted" = false ELSE true END
		and (soOrderInfo."Status" = 'SO_ST_CANCEL' 
		or soOrderInfo."Status" = 'SO_ST_FAILED' 
		or soOrderInfo."Status" = 'SO_ST_DELIVERED'
		or soOrderInfo."Status" = 'SO_ST_PARTIALDELIVERED')
;
END $func$;
SELECT
    *
FROM
    collectrawso('2023-01-05', 'BLS1', 'true')
LIMIT 100;